name: Setup workspace
description: setup Node, and install dependencies

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v2
      with:
        version: latest

    - uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'pnpm'

    - run: pnpm install
      shell: bash
