name: Deploy Storybook to Github Pages
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
jobs:
  deploy-storybook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout

      - id: setup
        uses: ./.github/actions/setup_workspace

      - run: yarn build-storybook --quiet

      - name: Deploy storybook
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/storybook
          publish_branch: static-pages
