name: NPM Publish

on:
  push:
    branches:
      - master
      - main

jobs:
  release_build:
    name: Release Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - id: setup
        uses: ./.github/actions/setup_workspace

      - run: pnpm type-check

      - run: pnpm test

      - run: pnpm build

      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist

  release_publish:
    name: Release Publish
    needs: release_build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - id: setup
        uses: ./.github/actions/setup_workspace

      - uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist

      - run: pnpm setup

      - run: pnpm add -g semantic-release @semantic-release/github conventional-changelog-conventionalcommits

      - run: pnpm exec semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
