name: NPM Publish

on:
  push:
    branches:
      - master
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - id: setup
        uses: ./.github/actions/setup_workspace

      - run: yarn type-check

      - run: yarn test

      - run: yarn build

      - name: Semantic Release
        id: semantic_release
        uses: cycjimmy/semantic-release-action@v2
        with: # You can specify specifying version range for the extra plugins if you prefer.
          extra_plugins: |
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - id: publish
        if: steps.semantic_release.outputs.new_release_published == 'true'
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: ./dist/package.json
