name: Validate Pull Requests

on:
  pull_request:

jobs:
  validate:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - id: setup
        uses: ./.github/actions/setup_workspace

      - run: pnpm type-check

      - run: pnpm test

  build:
    name: Build the lib
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - id: setup
        uses: ./.github/actions/setup_workspace

      - run: pnpm build

  build-storybook:
    name: Build the storybook
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - id: setup
        uses: ./.github/actions/setup_workspace

      - run: pnpm build-storybook --quiet
